{% set name = "deeptime" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}-ml/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 65a3787be549d749e10c4e6a1dffc42bb1b1ecbc95118bd028cf79fdfa2d5f5c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - cython
    - pip
    - numpy
    - scipy
    - pybind11
    - intel-openmp  # [osx]
    - llvm-openmp  # [osx]
    - libgomp  # [linux]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-learn
    - intel-openmp  # [osx]

test:
  imports:
    - deeptime

about:
  home: https://github.com/deeptime-ml/deeptime
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python library for analysis of time series data including dimensionality reduction, clustering, and Markov model estimation.

  description: |
    Deeptime is a Python library for analysis for time series data. 
    In particular, methods for dimensionality reduction, clustering, 
    and Markov model estimation are implemented. It is available for Python 3.6+.
  doc_url: https://deeptime-ml.github.io/
  dev_url: https://github.com/deeptime-ml/deeptime

extra:
  recipe-maintainers:
    - clonker
    - marscher
