{% set name = "deeptime" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}-ml/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b2bcb96a11445a1667709a92a33c4bc3f84dc1afbb232ff29dfaf473eb26c08c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - cython
    - pip
    - numpy
    - scipy
    - pybind11
    - llvm-openmp  # [osx]
    - libgomp  # [linux]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-learn
    - threadpoolctl

test:
  imports:
    - deeptime

about:
  home: https://github.com/deeptime-ml/deeptime
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python library for analysis of time series data including dimensionality reduction, clustering, and Markov model estimation.

  description: |
    Deeptime is a Python library for analysis for time series data. 
    In particular, methods for dimensionality reduction, clustering, 
    and Markov model estimation are implemented.
  doc_url: https://deeptime-ml.github.io/
  dev_url: https://github.com/deeptime-ml/deeptime

extra:
  recipe-maintainers:
    - clonker
    - marscher
